version: '3.8'
services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_DATABASE: mcm
      MYSQL_USER: mcm
      MYSQL_PASSWORD: clave_segura
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    env_file:
      - server/.env
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
volumes:
  dbdata:
  uploads:
