version: '3.8'
services:
  db:
    image: mariadb:11
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
    entrypoint: ["sh", "-c", "echo MYSQL_USER=$MYSQL_USER; echo MYSQL_PASSWORD=$MYSQL_PASSWORD; echo MYSQL_DATABASE=$MYSQL_DATABASE; exec docker-entrypoint.sh mysqld"]
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
volumes:
  dbdata:
  uploads:
