services:
  db:
    image: mariadb:11
    restart: always
    env_file:
      - .env
    # Las variables de MariaDB se leen directamente del archivo .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - uploads:/app/uploads
volumes:
  dbdata:
  uploads:
