---
- hosts: mcm_servers
  become: yes
  vars:
    app_dir: /opt/mcm
    repo_url: "https://github.com/example/mcm.git"
    node_version: "18.x"
  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Clone repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Install server dependencies
      npm:
        path: "{{ app_dir }}/server"
        production: yes

    - name: Install client dependencies
      npm:
        path: "{{ app_dir }}/client"

    - name: Build React client
      command: npm run build
      args:
        chdir: "{{ app_dir }}/client"

    - name: Start backend with pm2
      command: pm2 start index.js --name mcm-backend
      args:
        chdir: "{{ app_dir }}/server"
      register: pm2_backend
      failed_when: false

    - name: Start frontend with pm2
      command: pm2 serve build 3000 --name mcm-frontend
      args:
        chdir: "{{ app_dir }}/client"
      register: pm2_frontend
      failed_when: false

    - name: Save pm2 process list
      command: pm2 save
      when: pm2_backend.rc == 0 or pm2_frontend.rc == 0
